name: Workflow A (Ping)
on:
  push:
    branches:
      - main

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Workflow B
      uses: abystoma/event-usage/.github/workflows/pong.yml@main
      with:
        ping: 'PONG!'
